services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=${APP_NAME}
    deploy:
      replicas: 20
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 24

volumes:
  dbData:

networks:
  default:
      name: concurrent_counter_network