services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=${APP_NAME}
    deploy:
      replicas: 20
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbData:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 24

  # For monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - mysql_metric_exporter
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards/dashboards:/etc/dashboards
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus

  mysql_metric_exporter:
    image: prom/mysqld-exporter
    ports:
      - 9104:9104
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQLD_EXPORTER_PASSWORD=password
    volumes:
      - ./monitoring/mysql_exporter/.my.cnf:/.my.cnf

volumes:
  dbData:

networks:
  default:
      name: concurrent_counter_network